import { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import BannerSlider from '../../components/BannerSlider'
import Cart from '../../components/Cart'
import CategorySidebar from '../../components/CategorySidebar'
import Header from '../../components/Header'
import NavbarMenu from '../../components/NavbarMenu'
import Container from '../../components/styledComponents/Container'
import UserSidebar from '../../components/UserSidebar'

const User: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Gao Gram</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <script src='../path/to/flowbite/dist/flowbite.js' defer></script>
        <script
          src='https://unpkg.com/flowbite@1.5.3/dist/flowbite.js'
          defer
        ></script>
      </Head>
      <div className='sticky top-0'>
        {/* Header */}
        <Header />
        {/* Navbar */}
        <NavbarMenu />
        {/* Sidebar */}
        <UserSidebar />
      </div>

      <Container>
        <div className='md:-mt-[800px] '>
          <div className='bg-gray-100 rounded px-10 py-4 mt-5'>
            <div className='border-b-2 pb-2 md:flex justify-between items-center '>
              <div>
                <p>
                  Order{' '}
                  <span className='text-blue-400 font-bold'>#58964321845</span>{' '}
                </p>
                <p>Placed on 06 Sep 2022 16:08:11</p>
              </div>
              <div className='cursor-pointer'>
                <h3 className='text-blue-400 '>MANAGE</h3>
              </div>
            </div>

            <div className='md:flex gap-5 justify-between mt-10'>
              <div className='mb-4 md:mb-0 '>
                <img
                  height={100}
                  width={100}
                  src='https://static-01.daraz.com.bd/p/mdc/907b4aa190be73cd91e4f39754c7d64f.jpg'
                  alt=''
                />
              </div>
              <div className='mb-4 md:mb-0'>
                <p>Custom Tape Tennis Cricket Bat Solid Wood Direct Handle</p>
              </div>
              <div className='mb-4 md:mb-0 flex justify-between items-center md:block'>
                <p>
                  <span className='text-gray-400 mr-2'>Qty:</span>2
                </p>
                <span className='bg-gray-200 px-4 py-1 rounded-2xl md:hidden'>
                  Delivered
                </span>
              </div>
              <div className='mb-4 md:mb-0 hidden md:block'>
                <span className='bg-gray-200 px-4 py-1 rounded-2xl'>
                  Delivered
                </span>
              </div>
              <div className='mb-4 md:mb-0'>
                <p>Delivered on 11 Sep 2022</p>
              </div>
            </div>
          </div>
          <div className='bg-gray-100 rounded px-10 py-4 mt-5'>
            <div className='border-b-2 pb-2 md:flex justify-between items-center '>
              <div>
                <p>
                  Order{' '}
                  <span className='text-blue-400 font-bold'>#58964321845</span>{' '}
                </p>
                <p>Placed on 06 Sep 2022 16:08:11</p>
              </div>
              <div className='cursor-pointer'>
                <h3 className='text-blue-400 '>MANAGE</h3>
              </div>
            </div>

            <div className='md:flex gap-5 justify-between mt-10'>
              <div className='mb-4 md:mb-0 '>
                <img
                  height={100}
                  width={100}
                  src='https://static-01.daraz.com.bd/p/mdc/907b4aa190be73cd91e4f39754c7d64f.jpg'
                  alt=''
                />
              </div>
              <div className='mb-4 md:mb-0'>
                <p>Custom Tape Tennis Cricket Bat Solid Wood Direct Handle</p>
              </div>
              <div className='mb-4 md:mb-0 flex justify-between items-center md:block'>
                <p>
                  <span className='text-gray-400 mr-2'>Qty:</span>2
                </p>
                <span className='bg-gray-200 px-4 py-1 rounded-2xl md:hidden'>
                  Delivered
                </span>
              </div>
              <div className='mb-4 md:mb-0 hidden md:block'>
                <span className='bg-gray-200 px-4 py-1 rounded-2xl'>
                  Delivered
                </span>
              </div>
              <div className='mb-4 md:mb-0'>
                <p>Delivered on 11 Sep 2022</p>
              </div>
            </div>
          </div>
          <div className='bg-gray-100 rounded px-10 py-4 mt-5'>
            <div className='border-b-2 pb-2 md:flex justify-between items-center '>
              <div>
                <p>
                  Order{' '}
                  <span className='text-blue-400 font-bold'>#58964321845</span>{' '}
                </p>
                <p>Placed on 06 Sep 2022 16:08:11</p>
              </div>
              <div className='cursor-pointer'>
                <h3 className='text-blue-400 '>MANAGE</h3>
              </div>
            </div>

            <div className='md:flex gap-5 justify-between mt-10'>
              <div className='mb-4 md:mb-0 '>
                <img
                  height={100}
                  width={100}
                  src='https://static-01.daraz.com.bd/p/mdc/907b4aa190be73cd91e4f39754c7d64f.jpg'
                  alt=''
                />
              </div>
              <div className='mb-4 md:mb-0'>
                <p>Custom Tape Tennis Cricket Bat Solid Wood Direct Handle</p>
              </div>
              <div className='mb-4 md:mb-0 flex justify-between items-center md:block'>
                <p>
                  <span className='text-gray-400 mr-2'>Qty:</span>2
                </p>
                <span className='bg-gray-200 px-4 py-1 rounded-2xl md:hidden'>
                  Delivered
                </span>
              </div>
              <div className='mb-4 md:mb-0 hidden md:block'>
                <span className='bg-gray-200 px-4 py-1 rounded-2xl'>
                  Delivered
                </span>
              </div>
              <div className='mb-4 md:mb-0'>
                <p>Delivered on 11 Sep 2022</p>
              </div>
            </div>
          </div>
          <div className='bg-gray-100 rounded px-10 py-4 mt-5'>
            <div className='border-b-2 pb-2 md:flex justify-between items-center '>
              <div>
                <p>
                  Order{' '}
                  <span className='text-blue-400 font-bold'>#58964321845</span>{' '}
                </p>
                <p>Placed on 06 Sep 2022 16:08:11</p>
              </div>
              <div className='cursor-pointer'>
                <h3 className='text-blue-400 '>MANAGE</h3>
              </div>
            </div>

            <div className='md:flex gap-5 justify-between mt-10'>
              <div className='mb-4 md:mb-0 '>
                <img
                  height={100}
                  width={100}
                  src='https://static-01.daraz.com.bd/p/mdc/907b4aa190be73cd91e4f39754c7d64f.jpg'
                  alt=''
                />
              </div>
              <div className='mb-4 md:mb-0'>
                <p>Custom Tape Tennis Cricket Bat Solid Wood Direct Handle</p>
              </div>
              <div className='mb-4 md:mb-0 flex justify-between items-center md:block'>
                <p>
                  <span className='text-gray-400 mr-2'>Qty:</span>2
                </p>
                <span className='bg-gray-200 px-4 py-1 rounded-2xl md:hidden'>
                  Delivered
                </span>
              </div>
              <div className='mb-4 md:mb-0 hidden md:block'>
                <span className='bg-gray-200 px-4 py-1 rounded-2xl'>
                  Delivered
                </span>
              </div>
              <div className='mb-4 md:mb-0'>
                <p>Delivered on 11 Sep 2022</p>
              </div>
            </div>
          </div>
          <div className='bg-gray-100 rounded px-10 py-4 mt-5'>
            <div className='border-b-2 pb-2 md:flex justify-between items-center '>
              <div>
                <p>
                  Order{' '}
                  <span className='text-blue-400 font-bold'>#58964321845</span>{' '}
                </p>
                <p>Placed on 06 Sep 2022 16:08:11</p>
              </div>
              <div className='cursor-pointer'>
                <h3 className='text-blue-400 '>MANAGE</h3>
              </div>
            </div>

            <div className='md:flex gap-5 justify-between mt-10'>
              <div className='mb-4 md:mb-0 '>
                <img
                  height={100}
                  width={100}
                  src='https://static-01.daraz.com.bd/p/mdc/907b4aa190be73cd91e4f39754c7d64f.jpg'
                  alt=''
                />
              </div>
              <div className='mb-4 md:mb-0'>
                <p>Custom Tape Tennis Cricket Bat Solid Wood Direct Handle</p>
              </div>
              <div className='mb-4 md:mb-0 flex justify-between items-center md:block'>
                <p>
                  <span className='text-gray-400 mr-2'>Qty:</span>2
                </p>
                <span className='bg-gray-200 px-4 py-1 rounded-2xl md:hidden'>
                  Delivered
                </span>
              </div>
              <div className='mb-4 md:mb-0 hidden md:block'>
                <span className='bg-gray-200 px-4 py-1 rounded-2xl'>
                  Delivered
                </span>
              </div>
              <div className='mb-4 md:mb-0'>
                <p>Delivered on 11 Sep 2022</p>
              </div>
            </div>
          </div>
        </div>
      </Container>
    </div>
  )
}
export default User
