import type { NextPage } from 'next'
import Head from 'next/head'
import BannerSlider from '../components/BannerSlider'
import Cart from '../components/Cart'
import CategorySidebar from '../components/CategorySidebar'
import FeatureCard from '../components/FeatureCard'
import Footer from '../components/Footer'

import Header from '../components/Header'
import NavbarMenu from '../components/NavbarMenu'
import Container from '../components/styledComponents/Container'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Gao Gram</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <script src='../path/to/flowbite/dist/flowbite.js' defer></script>
        <script
          src='https://unpkg.com/flowbite@1.5.3/dist/flowbite.js'
          defer
        ></script>
      </Head>
      <div className='sticky top-0'>
        {/* Header */}
        <Header />
        {/* Navbar */}
        <NavbarMenu />
        {/* Sidebar */}
        <CategorySidebar />
      </div>

      <Cart />

      <Container>
        <div className='OthersContent'>
          <div className='flex flex-col lg:flex-row gap-5 my-10 lg:h-[400px]'>
            <div className='w-full lg:w-[70%] h-full'>
              <BannerSlider />
            </div>

            <div className='w-full lg:w-[30%] flex flex-col gap-3 h-full justify-center'>
              <FeatureCard />
              <FeatureCard />
              <FeatureCard />
            </div>
          </div>

          {/* all content goes here */}
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam
            laudantium accusantium autem nesciunt ex expedita alias accusamus
            voluptates magni? Laborum, dolorum. Cupiditate, recusandae veniam
            beatae debitis eos ex ducimus eum officiis illum rerum incidunt
            amet! Id, repellat distinctio? Inventore harum consectetur
            praesentium? Sit quaerat voluptates tempora aperiam, pariatur
            exercitationem necessitatibus vel quis quod hic neque. Impedit harum
            cumque quos iste soluta ipsum quas ipsa quisquam vel tenetur iure
            voluptatibus ad repellat, alias labore. Facere quibusdam ad quisquam
            voluptas laudantium aliquid ratione sint illo ab recusandae fugiat,
            vitae voluptatibus vel odio cupiditate, voluptates corporis mollitia
            at esse quia quasi aliquam. Inventore! Lorem ipsum dolor sit amet
            consectetur adipisicing elit. Facere unde voluptatem nisi autem
            minima eius dolores quis quod eum ipsam incidunt adipisci, tempore,
            vitae cupiditate aut possimus nam deserunt dignissimos esse sed!
            Sequi aspernatur deleniti soluta consequatur voluptas consequuntur
            illo blanditiis quam ipsum, optio provident dicta at, voluptatem
            autem debitis sunt error! Reiciendis eum, minima vero unde rerum
            amet possimus ut iure accusamus perferendis, odio eveniet saepe hic
            harum. Sed eos earum numquam. Ducimus adipisci impedit, dolorem
            voluptas mollitia doloribus vero labore iure voluptatum quidem
            doloremque est facilis. Qui ea earum maxime voluptates, aliquid a
            illo hic cumque id iusto corrupti voluptatem? Pariatur, quod
            consequatur? Sunt, ab ad. Beatae molestiae iste eveniet dicta
            consectetur perspiciatis asperiores magnam. Excepturi asperiores
            cum, voluptates, omnis, non voluptate aut tempora quae officiis odit
            saepe enim error porro iusto quis nulla provident consequatur
            ratione molestiae dicta maxime delectus molestias placeat unde.
            Aliquam, vitae. Animi natus ratione minus, voluptatibus sequi
            excepturi culpa praesentium similique sed numquam quis quas
            recusandae eaque tempore doloribus eveniet repellendus ducimus quae.
            Quisquam in laborum provident possimus dicta nemo vel harum
            molestias, optio perspiciatis eum ad velit unde magnam nam modi
            eveniet! Error iusto, natus voluptas suscipit repellat amet, cumque
            nihil minima ipsa, fuga atque. Modi cupiditate exercitationem sunt
            ea iusto deserunt laborum harum doloremque ab nisi fugiat, expedita
            tenetur ex nam quasi incidunt cumque magnam aperiam? Possimus, quam
            nihil nam delectus magni tempora error velit reprehenderit quas non
            vitae, quo soluta porro aliquam minima hic iusto sit illum, esse
            impedit nulla. Odio, nemo animi ab fuga impedit unde a dolor! Ipsa
            delectus, animi nostrum quia ea placeat iusto atque debitis, totam
            dolor aspernatur repellendus minima eius iure nemo nihil officia
            nulla dolores! Iure provident eos eum porro libero mollitia
            exercitationem asperiores aut delectus pariatur est dolore deserunt,
            tempore autem? Autem quia voluptatem corrupti eius odio cum quam
            est, voluptates temporibus provident, porro ea veniam culpa. Fuga
            quae corrupti explicabo quam nobis. Quas repellendus accusantium
            labore harum quisquam officiis ab, numquam consectetur, molestias
            rem animi, magni corrupti delectus natus neque! Eum id eveniet saepe
            modi voluptatibus alias impedit dolorem, explicabo quia natus
            tenetur ipsam, nihil eaque autem ut? Beatae mollitia possimus quidem
            exercitationem in natus sed laboriosam. Illo possimus molestias
            repudiandae laudantium, ullam eveniet quae dolor odit commodi
            debitis quia eaque tempora, nihil numquam ipsam minima architecto.
            Labore asperiores illo error, dolorem libero, sunt qui blanditiis,
            iure praesentium quod assumenda! Voluptate, sed reprehenderit! Eius
            quos quae, omnis nostrum voluptatibus provident perspiciatis
            molestias recusandae architecto amet. Maxime ut ipsam aut, tempora
            laboriosam pariatur ipsa, aspernatur velit nemo fugit, nobis
            temporibus ipsum? Tempora, iusto similique? Minus velit modi quidem
            maiores sunt neque odio rerum pariatur voluptas dolor, vel magnam
            aperiam delectus atque iure accusantium? Nemo facere eum eius veniam
            corrupti ab esse, expedita cumque? Praesentium facilis eveniet rerum
            laborum id distinctio quasi. Natus labore consequatur ullam, esse
            debitis vero excepturi repellat illum nobis iusto modi deserunt,
            facilis asperiores corrupti eos doloribus atque laudantium pariatur
            dolores iure facere eum quaerat voluptatum! Molestiae delectus
            laborum quasi tempore ratione totam repudiandae, aspernatur odit,
            sint explicabo dicta. Quibusdam impedit repudiandae corporis
            cupiditate quos atque! In officiis nisi dolore eos repellat fuga
            totam beatae similique recusandae? Culpa maxime aspernatur, libero,
            ab consequuntur reiciendis illo, incidunt ipsa exercitationem qui
            dolorum? Ratione, dolorum quaerat maiores molestiae deleniti
            praesentium magnam, est asperiores, temporibus laborum ipsam!
            Accusamus, ab eius voluptatum delectus unde et iusto voluptas sint
            repudiandae corrupti, dolorum ipsum nesciunt aliquid a neque
            repellendus? Esse tenetur ducimus, enim placeat saepe ut nostrum eum
            cumque consectetur alias sapiente aspernatur perspiciatis eaque. Eum
            at odio quia hic adipisci reiciendis pariatur culpa placeat a ab
            vitae, quam natus ipsam error ipsum cumque. Repellat perferendis,
            eum impedit ad architecto voluptatum hic, molestias excepturi optio,
            quidem inventore quaerat. Harum inventore voluptatum hic, ipsa odio
            ducimus dolores ratione veniam soluta assumenda perferendis nesciunt
            quos recusandae. Dolorum voluptatibus qui rerum omnis laborum
            tenetur, nesciunt quidem vitae inventore veritatis? Aut eius non
            maiores harum sequi rem labore cumque, nulla cupiditate quas
            explicabo architecto ipsa doloremque alias expedita. Quo nostrum
            molestiae voluptatum molestias, a inventore ut in nemo atque ducimus
            rem reiciendis quis assumenda doloribus dignissimos doloremque vero.
            Unde, ad exercitationem architecto similique corrupti vitae!
            Blanditiis recusandae itaque iste porro ipsum beatae aliquam, illo
            repellendus inventore incidunt ut. Mollitia minus odio eveniet
            nesciunt quia ipsam nisi velit ipsa consectetur sequi cupiditate
            earum, pariatur amet dolores ad unde aliquid corrupti omnis,
            accusamus, est quis nam? Quaerat in reprehenderit sapiente! Natus
            iure, sapiente repellat non molestias odio expedita laudantium
            consectetur recusandae accusamus eum rem tempora quod debitis
            commodi impedit officiis quo omnis similique ullam aspernatur, hic,
            ea maxime? Voluptatibus sequi nobis dolorem id sed similique
            maiores, reiciendis amet quam cumque ea architecto ipsam explicabo
            iusto placeat at blanditiis hic a, dolorum cupiditate. Provident
            repudiandae libero blanditiis rerum nostrum aliquid laboriosam
            facilis nam quasi saepe. Consequuntur incidunt, minus necessitatibus
            enim error ullam quia, molestias accusamus praesentium architecto
            quidem a aut officiis. Vel est perferendis vero doloribus facere id
            nulla necessitatibus sunt at! Sit eligendi, harum accusamus ratione
            quasi ea, iusto in voluptatem dolore nam quam eius illum. Sapiente
            nulla corporis optio! Nihil velit porro perspiciatis, pariatur quas
            cum vel ipsum quam omnis dolorum eius, maiores esse unde
            consequuntur voluptatibus facere cumque, quisquam sapiente ex minima
            modi iste corrupti. Aliquid dicta minima nihil, voluptatum magnam
            nobis harum dolores molestiae earum et aut! Nostrum sit laborum
            voluptate nobis reprehenderit! Perspiciatis, velit veritatis
            expedita quam ullam tempore sapiente corrupti qui eum quas, dolorem
            sed nobis explicabo ad omnis architecto commodi officiis, provident
            fugiat aut saepe aspernatur vitae. Aperiam ipsam iusto ab iure
            laboriosam, nisi ut, officia enim sunt explicabo dolor similique,
            sapiente reiciendis in consectetur quae accusantium. Dolores eum
            quam voluptatem, harum magnam modi rerum libero obcaecati omnis
            sunt, aliquam, dolorum cupiditate! Commodi atque minima dolor
            tempore dolore soluta similique saepe eius magni porro qui sint
            numquam consequuntur amet veniam, sapiente adipisci! Obcaecati
            officiis aliquid, perferendis magni nesciunt quidem dolor ea hic at
            officia iusto voluptatem adipisci saepe veniam ad possimus error,
            animi assumenda recusandae laboriosam odio!
          </p>
        </div>
      </Container>
      <Footer />
    </div>
  )
}

export default Home
